# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - goimports
    - govet
    - staticcheck
    - gosec
    - cyclop
    - gocritic
    - depguard

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  depguard:
    rules:
      main:
        files: 
          - $all
          - "!$test"
        allow:
          - $gostd
          - "github.com/cristiano-pacheco/shoplist"
          - "github.com/go-playground/validator"
          - "github.com/spf13/cobra"
          - "github.com/gofiber/fiber"
          - "github.com/stretchr/testify"
          - "github.com/go-playground/universal-translator"
          - "github.com/go-playground/locales"
          - "github.com/golang-jwt/jwt"
          - "github.com/DATA-DOG/go-sqlmock"
          - "github.com/golang-migrate/migrate"
          - "github.com/joho/godotenv"
          - "github.com/caarlos0/env"
          - "github.com/go-mail/mail/v2"
          - "github.com/gofiber/swagger"
          - "github.com/contribsys/faktory_worker_go"
          - "github.com/contribsys/faktory/client"
          - "github.com/rabbitmq/amqp091-go"
          - "github.com/gofiber/contrib/otelfiber/v2"
          - "go.uber.org/fx"
          - "gorm.io/gorm"
          - "gorm.io/gorm/logger"
          - "gorm.io/driver/postgres"
          - "go.opentelemetry.io/otel/semconv/v1.26.0"
          - "go.opentelemetry.io/otel/trace"
          - "go.opentelemetry.io/otel/attribute"
          - "golang.org/x/crypto/bcrypt"
          - "go.opentelemetry.io/otel"
          - "go.opentelemetry.io/otel/propagation"
          - "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"
          - "go.opentelemetry.io/otel/sdk/resource"
          - "go.opentelemetry.io/otel/sdk/trace"

