services:
  gomodulith-postgres:
    image: postgres:16-alpine
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_DB: gomodulith
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    networks:
      - gomodulith_internal

networks:
  gomodulith_internal:
    name: gomodulith_internal

volumes:
  postgres:
