services:
  controlweb-postgres:
    image: postgres:16-alpine
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_DB: controlweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    networks:
      - controlweb_internal

networks:
  controlweb_internal:
    name: controlweb_internal

volumes:
  postgres:
