// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockHashServiceI is an autogenerated mock type for the HashServiceI type
type MockHashServiceI struct {
	mock.Mock
}

type MockHashServiceI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHashServiceI) EXPECT() *MockHashServiceI_Expecter {
	return &MockHashServiceI_Expecter{mock: &_m.Mock}
}

// CompareHashAndPassword provides a mock function with given fields: hashedPassword, password
func (_m *MockHashServiceI) CompareHashAndPassword(hashedPassword []byte, password []byte) error {
	ret := _m.Called(hashedPassword, password)

	if len(ret) == 0 {
		panic("no return value specified for CompareHashAndPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, []byte) error); ok {
		r0 = rf(hashedPassword, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHashServiceI_CompareHashAndPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompareHashAndPassword'
type MockHashServiceI_CompareHashAndPassword_Call struct {
	*mock.Call
}

// CompareHashAndPassword is a helper method to define mock.On call
//   - hashedPassword []byte
//   - password []byte
func (_e *MockHashServiceI_Expecter) CompareHashAndPassword(hashedPassword interface{}, password interface{}) *MockHashServiceI_CompareHashAndPassword_Call {
	return &MockHashServiceI_CompareHashAndPassword_Call{Call: _e.mock.On("CompareHashAndPassword", hashedPassword, password)}
}

func (_c *MockHashServiceI_CompareHashAndPassword_Call) Run(run func(hashedPassword []byte, password []byte)) *MockHashServiceI_CompareHashAndPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].([]byte))
	})
	return _c
}

func (_c *MockHashServiceI_CompareHashAndPassword_Call) Return(_a0 error) *MockHashServiceI_CompareHashAndPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHashServiceI_CompareHashAndPassword_Call) RunAndReturn(run func([]byte, []byte) error) *MockHashServiceI_CompareHashAndPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateFromPassword provides a mock function with given fields: password
func (_m *MockHashServiceI) GenerateFromPassword(password []byte) ([]byte, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromPassword")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) ([]byte, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashServiceI_GenerateFromPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateFromPassword'
type MockHashServiceI_GenerateFromPassword_Call struct {
	*mock.Call
}

// GenerateFromPassword is a helper method to define mock.On call
//   - password []byte
func (_e *MockHashServiceI_Expecter) GenerateFromPassword(password interface{}) *MockHashServiceI_GenerateFromPassword_Call {
	return &MockHashServiceI_GenerateFromPassword_Call{Call: _e.mock.On("GenerateFromPassword", password)}
}

func (_c *MockHashServiceI_GenerateFromPassword_Call) Run(run func(password []byte)) *MockHashServiceI_GenerateFromPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockHashServiceI_GenerateFromPassword_Call) Return(_a0 []byte, _a1 error) *MockHashServiceI_GenerateFromPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashServiceI_GenerateFromPassword_Call) RunAndReturn(run func([]byte) ([]byte, error)) *MockHashServiceI_GenerateFromPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRandomBytes provides a mock function with given fields:
func (_m *MockHashServiceI) GenerateRandomBytes() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRandomBytes")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHashServiceI_GenerateRandomBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRandomBytes'
type MockHashServiceI_GenerateRandomBytes_Call struct {
	*mock.Call
}

// GenerateRandomBytes is a helper method to define mock.On call
func (_e *MockHashServiceI_Expecter) GenerateRandomBytes() *MockHashServiceI_GenerateRandomBytes_Call {
	return &MockHashServiceI_GenerateRandomBytes_Call{Call: _e.mock.On("GenerateRandomBytes")}
}

func (_c *MockHashServiceI_GenerateRandomBytes_Call) Run(run func()) *MockHashServiceI_GenerateRandomBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHashServiceI_GenerateRandomBytes_Call) Return(_a0 []byte, _a1 error) *MockHashServiceI_GenerateRandomBytes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHashServiceI_GenerateRandomBytes_Call) RunAndReturn(run func() ([]byte, error)) *MockHashServiceI_GenerateRandomBytes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHashServiceI creates a new instance of MockHashServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHashServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHashServiceI {
	mock := &MockHashServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
