global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']

  # Add your application metrics endpoint here
  - job_name: 'shoplist'
    static_configs:
      - targets: ['localhost:9000']