// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPasswordValidator is an autogenerated mock type for the PasswordValidator type
type MockPasswordValidator struct {
	mock.Mock
}

type MockPasswordValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordValidator) EXPECT() *MockPasswordValidator_Expecter {
	return &MockPasswordValidator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: password
func (_m *MockPasswordValidator) Validate(password string) error {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordValidator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockPasswordValidator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordValidator_Expecter) Validate(password interface{}) *MockPasswordValidator_Validate_Call {
	return &MockPasswordValidator_Validate_Call{Call: _e.mock.On("Validate", password)}
}

func (_c *MockPasswordValidator_Validate_Call) Run(run func(password string)) *MockPasswordValidator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPasswordValidator_Validate_Call) Return(_a0 error) *MockPasswordValidator_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordValidator_Validate_Call) RunAndReturn(run func(string) error) *MockPasswordValidator_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordValidator creates a new instance of MockPasswordValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordValidator {
	mock := &MockPasswordValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
