// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockValidateI is an autogenerated mock type for the ValidateI type
type MockValidateI struct {
	mock.Mock
}

type MockValidateI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidateI) EXPECT() *MockValidateI_Expecter {
	return &MockValidateI_Expecter{mock: &_m.Mock}
}

// Struct provides a mock function with given fields: s
func (_m *MockValidateI) Struct(s interface{}) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidateI_Struct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Struct'
type MockValidateI_Struct_Call struct {
	*mock.Call
}

// Struct is a helper method to define mock.On call
//   - s interface{}
func (_e *MockValidateI_Expecter) Struct(s interface{}) *MockValidateI_Struct_Call {
	return &MockValidateI_Struct_Call{Call: _e.mock.On("Struct", s)}
}

func (_c *MockValidateI_Struct_Call) Run(run func(s interface{})) *MockValidateI_Struct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockValidateI_Struct_Call) Return(_a0 error) *MockValidateI_Struct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidateI_Struct_Call) RunAndReturn(run func(interface{}) error) *MockValidateI_Struct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidateI creates a new instance of MockValidateI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidateI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidateI {
	mock := &MockValidateI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
