// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cristiano-pacheco/go-modulith/internal/module/billing/model"
	repository "github.com/cristiano-pacheco/go-modulith/internal/module/billing/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockBillingRepositoryI is an autogenerated mock type for the BillingRepositoryI type
type MockBillingRepositoryI struct {
	mock.Mock
}

type MockBillingRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillingRepositoryI) EXPECT() *MockBillingRepositoryI_Expecter {
	return &MockBillingRepositoryI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockBillingRepositoryI) Create(ctx context.Context, _a1 model.BillingModel) (*model.BillingModel, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.BillingModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BillingModel) (*model.BillingModel, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BillingModel) *model.BillingModel); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BillingModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BillingModel) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRepositoryI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBillingRepositoryI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.BillingModel
func (_e *MockBillingRepositoryI_Expecter) Create(ctx interface{}, _a1 interface{}) *MockBillingRepositoryI_Create_Call {
	return &MockBillingRepositoryI_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockBillingRepositoryI_Create_Call) Run(run func(ctx context.Context, _a1 model.BillingModel)) *MockBillingRepositoryI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BillingModel))
	})
	return _c
}

func (_c *MockBillingRepositoryI_Create_Call) Return(_a0 *model.BillingModel, _a1 error) *MockBillingRepositoryI_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillingRepositoryI_Create_Call) RunAndReturn(run func(context.Context, model.BillingModel) (*model.BillingModel, error)) *MockBillingRepositoryI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, _a1
func (_m *MockBillingRepositoryI) Delete(ctx context.Context, _a1 model.BillingModel) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BillingModel) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRepositoryI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBillingRepositoryI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.BillingModel
func (_e *MockBillingRepositoryI_Expecter) Delete(ctx interface{}, _a1 interface{}) *MockBillingRepositoryI_Delete_Call {
	return &MockBillingRepositoryI_Delete_Call{Call: _e.mock.On("Delete", ctx, _a1)}
}

func (_c *MockBillingRepositoryI_Delete_Call) Run(run func(ctx context.Context, _a1 model.BillingModel)) *MockBillingRepositoryI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BillingModel))
	})
	return _c
}

func (_c *MockBillingRepositoryI_Delete_Call) Return(_a0 error) *MockBillingRepositoryI_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRepositoryI_Delete_Call) RunAndReturn(run func(context.Context, model.BillingModel) error) *MockBillingRepositoryI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindList provides a mock function with given fields: ctx, filters
func (_m *MockBillingRepositoryI) FindList(ctx context.Context, filters repository.BillingSearchFilters) []*model.BillingModel {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for FindList")
	}

	var r0 []*model.BillingModel
	if rf, ok := ret.Get(0).(func(context.Context, repository.BillingSearchFilters) []*model.BillingModel); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.BillingModel)
		}
	}

	return r0
}

// MockBillingRepositoryI_FindList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindList'
type MockBillingRepositoryI_FindList_Call struct {
	*mock.Call
}

// FindList is a helper method to define mock.On call
//   - ctx context.Context
//   - filters repository.BillingSearchFilters
func (_e *MockBillingRepositoryI_Expecter) FindList(ctx interface{}, filters interface{}) *MockBillingRepositoryI_FindList_Call {
	return &MockBillingRepositoryI_FindList_Call{Call: _e.mock.On("FindList", ctx, filters)}
}

func (_c *MockBillingRepositoryI_FindList_Call) Run(run func(ctx context.Context, filters repository.BillingSearchFilters)) *MockBillingRepositoryI_FindList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(repository.BillingSearchFilters))
	})
	return _c
}

func (_c *MockBillingRepositoryI_FindList_Call) Return(_a0 []*model.BillingModel) *MockBillingRepositoryI_FindList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRepositoryI_FindList_Call) RunAndReturn(run func(context.Context, repository.BillingSearchFilters) []*model.BillingModel) *MockBillingRepositoryI_FindList_Call {
	_c.Call.Return(run)
	return _c
}

// FindOneByID provides a mock function with given fields: ctx, ID
func (_m *MockBillingRepositoryI) FindOneByID(ctx context.Context, ID uint64) (*model.BillingModel, error) {
	ret := _m.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for FindOneByID")
	}

	var r0 *model.BillingModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*model.BillingModel, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *model.BillingModel); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BillingModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRepositoryI_FindOneByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneByID'
type MockBillingRepositoryI_FindOneByID_Call struct {
	*mock.Call
}

// FindOneByID is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uint64
func (_e *MockBillingRepositoryI_Expecter) FindOneByID(ctx interface{}, ID interface{}) *MockBillingRepositoryI_FindOneByID_Call {
	return &MockBillingRepositoryI_FindOneByID_Call{Call: _e.mock.On("FindOneByID", ctx, ID)}
}

func (_c *MockBillingRepositoryI_FindOneByID_Call) Run(run func(ctx context.Context, ID uint64)) *MockBillingRepositoryI_FindOneByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockBillingRepositoryI_FindOneByID_Call) Return(_a0 *model.BillingModel, _a1 error) *MockBillingRepositoryI_FindOneByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillingRepositoryI_FindOneByID_Call) RunAndReturn(run func(context.Context, uint64) (*model.BillingModel, error)) *MockBillingRepositoryI_FindOneByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *MockBillingRepositoryI) Update(ctx context.Context, _a1 model.BillingModel) (*model.BillingModel, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.BillingModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.BillingModel) (*model.BillingModel, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.BillingModel) *model.BillingModel); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BillingModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.BillingModel) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRepositoryI_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBillingRepositoryI_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 model.BillingModel
func (_e *MockBillingRepositoryI_Expecter) Update(ctx interface{}, _a1 interface{}) *MockBillingRepositoryI_Update_Call {
	return &MockBillingRepositoryI_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *MockBillingRepositoryI_Update_Call) Run(run func(ctx context.Context, _a1 model.BillingModel)) *MockBillingRepositoryI_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.BillingModel))
	})
	return _c
}

func (_c *MockBillingRepositoryI_Update_Call) Return(_a0 *model.BillingModel, _a1 error) *MockBillingRepositoryI_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillingRepositoryI_Update_Call) RunAndReturn(run func(context.Context, model.BillingModel) (*model.BillingModel, error)) *MockBillingRepositoryI_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBillingRepositoryI creates a new instance of MockBillingRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillingRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillingRepositoryI {
	mock := &MockBillingRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
